CREATE TABLE Location (
POSTAL_CODE VARCHAR2(10) PRIMARY KEY,
COUNTRY VARCHAR2(50) NOT NULL
);

CREATE TABLE Users (
USER_ID NUMBER (10) PRIMARY KEY,
USERNAME VARCHAR2 (50) NOT NULL,
EMAIL VARCHAR2 (50) NOT NULL,
PASSWORD_HASH VARCHAR2 (100) NOT NULL,
FIRST_NAME VARCHAR2 (20) NOT NULL,
LAST_NAME VARCHAR2 (20) NOT NULL,
BIRTH_DATE DATE,
GENDER CHAR (1),
POSTAL_CODE VARCHAR2 (10),
CREATED_AT DATE DEFAULT SYSDATE,
BIO VARCHAR2 (500),
PROFILE_PICTURE VARCHAR2 (500),
CONSTRAINT chk_password_hash_length CHECK (LENGTH (PASSWORD_HASH) >= 6),
CONSTRAINT une_username UNIQUE (USERNAME),
CONSTRAINT une_email UNIQUE (EMAIL),
CONSTRAINT chk_users_gender CHECK (GENDER IN ('M','F')),
CONSTRAINT fk_users_location FOREIGN KEY (POSTAL_CODE) REFERENCES Location (POSTAL_CODE)
);

CREATE TABLE Posts (
POST_ID NUMBER (10) PRIMARY KEY,
USER_ID NUMBER (10) NOT NULL,
CONTENT VARCHAR2(700) NOT NULL,
MEDIA_TYPE VARCHAR2(5),
MEDIA_URL VARCHAR2(500),
TIME_STAMP DATE DEFAULT SYSDATE,
CONSTRAINT chk_posts_media_type CHECK (MEDIA_TYPE IN ('TEXT', 'IMAGE', 'VIDEO')),
CONSTRAINT fk_posts_user FOREIGN KEY (USER_ID) REFERENCES Users(USER_ID) ON DELETE CASCADE
);

CREATE TABLE Comments (
COMMENT_ID NUMBER (10) PRIMARY KEY,
POST_ID NUMBER (10) NOT NULL,
COMMENTER_ID NUMBER (10) NOT NULL,
COMMENT_CONTENT VARCHAR2(700) NOT NULL,
COMMENT_DATE DATE DEFAULT SYSDATE,
CONSTRAINT fk_comments_post FOREIGN KEY (POST_ID) REFERENCES Posts(POST_ID) ON DELETE CASCADE,
CONSTRAINT fk_comments_user FOREIGN KEY (COMMENTER_ID) REFERENCES Users(USER_ID) ON DELETE CASCADE
);

CREATE TABLE Post_Likes (
POST_LIKE_ID NUMBER (10) PRIMARY KEY,
POST_ID NUMBER (10) NOT NULL,
POSTLIKE_USER_ID NUMBER (10) NOT NULL,
POSTLIKE_DATE DATE DEFAULT SYSDATE,
UNIQUE (POST_ID, POSTLIKE_USER_ID),
CONSTRAINT fk_post_likes_post FOREIGN KEY (POST_ID) REFERENCES Posts(POST_ID) ON DELETE CASCADE,
CONSTRAINT fk_post_likes_user FOREIGN KEY (POSTLIKE_USER_ID) REFERENCES Users(USER_ID) ON DELETE CASCADE
);

CREATE TABLE Comment_Likes (
COMMENT_LIKE_ID NUMBER (10) PRIMARY KEY,
COMMENT_ID NUMBER (10) NOT NULL,
COMLIKE_USER_ID NUMBER (10) NOT NULL,
COMLIKE_DATE DATE DEFAULT SYSDATE,
UNIQUE (COMMENT_ID, COMLIKE_USER_ID),
CONSTRAINT fk_comment_likes_comment FOREIGN KEY (COMMENT_ID) REFERENCES Comments(COMMENT_ID) ON DELETE CASCADE,
CONSTRAINT fk_comment_likes_user FOREIGN KEY (COMLIKE_USER_ID) REFERENCES Users(USER_ID) ON DELETE CASCADE
);

CREATE TABLE Friendships (
FRIENDSHIP_ID NUMBER (10) PRIMARY KEY,
USER_ID NUMBER (10) NOT NULL,
FRIEND_ID NUMBER (10) NOT NULL,
FRIENDSHIP_DATE DATE DEFAULT SYSDATE,
CONSTRAINT chk_friendships_no_self CHECK (USER_ID != FRIEND_ID),
UNIQUE (USER_ID, FRIEND_ID),
CONSTRAINT fk_friendships_requester FOREIGN KEY (USER_ID) REFERENCES Users(USER_ID) ON DELETE CASCADE,
CONSTRAINT fk_friendships_addressee FOREIGN KEY (FRIEND_ID) REFERENCES Users(USER_ID) ON DELETE CASCADE   
);

CREATE TABLE Messages (
MESSAGE_ID NUMBER (10) PRIMARY KEY,
USER_ID NUMBER (10) NOT NULL,
RECEIVER_ID NUMBER (10) NOT NULL,
MESSAGE_CONTENT VARCHAR2(700) NOT NULL,
MESSAGE_TYPE VARCHAR2(8),
MESSAGE_MEDIA_URL VARCHAR2(500),
IS_READ NUMBER (1) DEFAULT 0,
MESSAGE_CREATED_AT DATE DEFAULT SYSDATE,
MESSAGE_READ_AT DATE,
CONSTRAINT chk_messages_type CHECK (MESSAGE_TYPE IN ('TEXT', 'IMAGE', 'VIDEO', 'AUDIO', 'DOCUMENT')),
CONSTRAINT chk_is_read CHECK (IS_READ IN (0 , 1)),
CONSTRAINT chk_messages_no_self CHECK (USER_ID != RECEIVER_ID),
CONSTRAINT fk_messages_sender FOREIGN KEY (USER_ID) REFERENCES Users(USER_ID) ON DELETE CASCADE,
CONSTRAINT fk_messages_receiver FOREIGN KEY (RECEIVER_ID) REFERENCES Users(USER_ID) ON DELETE CASCADE
);

CREATE TABLE Follows (
FOLLOW_ID NUMBER (10) PRIMARY KEY,
USER_ID NUMBER (10) NOT NULL,
FOLLOWED_ID NUMBER (10) NOT NULL,
FOLLOW_CREATED_AT DATE DEFAULT SYSDATE,
CONSTRAINT chk_follows_no_self CHECK (USER_ID != FOLLOWED_ID),
UNIQUE (USER_ID, FOLLOWED_ID),
CONSTRAINT fk_follows_follower FOREIGN KEY (USER_ID) REFERENCES Users(USER_ID) ON DELETE CASCADE,
CONSTRAINT fk_follows_followee FOREIGN KEY (FOLLOWED_ID) REFERENCES Users(USER_ID) ON DELETE CASCADE
);